apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            - name: DATABASE_HOST
              value: {{ .Values.env.DATABASE_HOST }}
            - name: DATABASE_NAME
              value: {{ .Values.env.DATABASE_NAME }}
            - name: DATABASE_USER
              value: {{ .Values.env.DATABASE_USER }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.env.DATABASE_PASSWORD }}
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.port }}